fix: dark mode in accordion
trendmicro-frontend/tonic-ui pull request #36
Opened 2020-02-10 09:31 UTC by roth1002

Before

![螢幕快照 2020-02-10 下午5 30 06](https://user-images.githubusercontent.com/8485590/74137602-14884100-4c2b-11ea-99bc-4ca61e34eb0c.png)

After

![螢幕快照 2020-02-10 下午5 30 21](https://user-images.githubusercontent.com/8485590/74137621-1baf4f00-4c2b-11ea-9bbc-8ff01c15014b.png)

2020-02-10 10:12 UTC, cheton requested changes

2020-02-10 10:12 UTC, cheton commented on packages/react-styled-core/src/Accordion/index.js
> +      _hover={_hover === null ? { bg: 'blackAlpha.10' } : _hover}
這個不應該用 blackAlpha，這是給 font color 用的

2020-02-10 10:12 UTC, cheton commented on packages/react-styled-core/src/Accordion/index.js
> +      _hover={_hover === null ? { bg: 'blackAlpha.10' } : _hover}
```jsx
const { colorMode } = useColorMode();
const hoverBg = {
    dark: 'xxx',
    white: 'ooo',
}[colorMode];
```

2020-02-10 16:25 UTC, cheton approved these changes

2020-02-11 02:14 UTC, austinhung81 approved these changes

2020-02-11 02:39 UTC, merged